FROM centos:7
RUN yum install -y \
  openssh-server \
  openssh-clients \
  iproute \
  which \
  net-tools \
  lsof \
  vim-enhanced \
  wget \
  git \
  && wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
