version: '3.0'
services:
  master:
    ports:
    - "${ANSIBLE_MASTER_PORT}:22"
    volumes:
    - ${VOLUME_HOME}/ansible/master:/root/ansible
    - ${VOLUME_HOME}/.bashrc:/root/.bashrc
    image: centos:7-dev
    command:
    - /bin/sh
    - -c
    - "${ANSIBLE_INIT_COMMAND}"
    restart: always
  agent1:
    ports:
    - "${ANSIBLE_AGENT1_PORT}:22"
    volumes:
    - ${VOLUME_HOME}/ansible/agent-1:/root/ansible
    - ${VOLUME_HOME}/.bashrc:/root/.bashrc
    image: centos:7-dev
    command:
    - /bin/sh
    - -c
    - "${ANSIBLE_INIT_COMMAND}"
    restart: always
  agent2:
    ports:
    - "${ANSIBLE_AGENT2_PORT}:22"
    volumes:
    - ${VOLUME_HOME}/ansible/agent-2:/root/ansible
    - ${VOLUME_HOME}/.bashrc:/root/.bashrc
    image: centos:7-dev
    command:
    - /bin/sh
    - -c
    - "${ANSIBLE_INIT_COMMAND}"
    restart: always
