version: '3.0'
services:
  java9:
    ports:
    - ${JAVA9_PORT}:${JAVA9_PORT}
    volumes:
    - ${VOLUME_HOME}/java:/home/java
    - ${VOLUME_HOME}/.bashrc:/root/.bashrc
    command:
    - /bin/sh
    - -c
    - "${INIT_COMMAND}"
    restart: always
    image: java:9-jdk
