version: '3.0'
services:
  jupyter:
    ports:
    - "${JUPYTER_PORT}:${JUPYTER_PORT}"
    volumes:
    - ${VOLUME_HOME}/jupyter/work:/home/jovyan/work
    - ${VOLUME_HOME}/.bashrc:/root/.bashrc
    image: jupyter/scipy-notebook:latest
    command:
    - /bin/sh
    - -c
    - "mkdir /home/jovyan/.jupyter; ${INIT_COMMAND}"
    restart: always
