version: '3.0'
services:
  jupyter:
    ports:
    - "31234:31234"
    volumes:
    - /Users/howu/Workspace/docker/volume/jupyter/work:/home/jovyan/work
    - /Users/howu/Workspace/docker/volume/.bashrc:/root/.bashrc 
    image: jupyter/scipy-notebook:latest
    command: 
    - /bin/sh
    - -c
    - "mkdir /home/jovyan/.jupyter; while true; do echo [`whoami`][`date '+%Y-%m-%d %H:%M:%S'`]: the container is alive; sleep 10; done"
    restart: always 
