# https://hub.docker.com/r/jupyter/datascience-notebook
# https://github.com/jupyter/docker-stacks
version: '3.0'
services:
  jupyter:
    ports:
    - ${JUPYTER_PORT}:8888
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    volumes:
    - ${VOLUME_HOME}/jupyter/workspace:/home/jovyan/work
    - ${VOLUME_HOME}/.bashrc:/root/.bashrc
    restart: always
    image: jupyter/datascience-notebook:2ce7c06a61a1
