version: '3.0'
services:
  jupyter:
    ports:
    - ${JUPYTER_PORT}:8080
    volumes:
    - ${VOLUME_HOME}/jupyter/workspace:/home/jupyter
    - ${VOLUME_HOME}/.bashrc:/root/.bashrc
    command:
    - /bin/sh
    - -c
    - "${JUPYTER_INIT_COMMAND}"
    restart: always
    image: centos_jupyter:0.1
