# Use root/example as user/password credentials
version: '3.1'
services:
  mongo:
    ports:
    - ${MONGO_PORT}:27017
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
    - ${VOLUME_HOME}/mongo/data/db:/data/db
    restart: always
    image: mongo:4.1.11
  mongo-express:
    ports:
    - ${MONGO_EXPRESS_PORT}:8081
    environment:
    - ME_CONFIG_MONGODB_ADMINUSERNAME=root
    - ME_CONFIG_MONGODB_ADMINPASSWORD=example
    restart: always
    image: mongo-express:0.49
