# https://hub.docker.com/_/nginx/
version: '3.0'
services:
  nginx:
    volumes:
     - ${VOLUME_HOME}/nginx/mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
     - ${NGINX_PORT}:80
    environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80
    command:
    - /bin/bash
    - -c
    - ${INIT_COMMAND}
    image: nginx:1.15.1
