version: '3.0'
services:
  nodejs:
    ports:
    - "31235:31235"
    volumes:
    - ${VOLUME_HOME}/nodejs:/root/nodejs
    - ${VOLUME_HOME}/.bashrc:/root/.bashrc
    image: node:latest
    command:
    - /bin/sh
    - -c
    - "${INIT_COMMAND}"
    restart: always
