version: '3.0'
services:
  organizr:
    ports:
    - ${ORGANIZR_PORT}:80 # To expose the HTTP port
    hostname: organizr
    volumes:
    - ${VOLUME_HOME}/organizr/config:/config
    - ${VOLUME_HOME}/.bashrc:/root/.bashrc
    restart: always
    image: organizrtools/organizr-v2
