version: '3.0'
services:
  plexserver:
    ports:
    - "32400:32400/tcp"
    - "3005:3005/tcp"
    - "8324:8324/tcp"
    - "32469:32469/tcp"
    - "1900:1900/udp"
    - "32410:32410/udp"
    - "32412:32412/udp"
    - "32413:32413/udp"
    - "32414:32414/udp"
    hostname: PlexServer
    volumes:
    - ${VOLUME_HOME}/plexserver/plex/database:/config
    - ${VOLUME_HOME}/plexserver/transcode/temp:/transcode
    - ${VOLUME_HOME}/plexserver/media:/data
    - ${VOLUME_HOME}/.bashrc:/root/.bashrc
    environment:
    - TZ="Asia/Shanghai"
    # - PLEX_CLAIM="<claimToken>"
    # - ADVERTISE_IP="http://<hostIPAddress>:32400/"
    - ADVERTISE_IP="http://10.201.132.30:32400/"
    restart: always
    image: plexinc/pms-docker:1.14.1.5488-cc260c476
