version: '3.0'
services:
  python:
    ports:
    - "31236:31236"
    volumes:
    - ${VOLUME_HOME}/python3.6.5:/root/python3.6.5
    - ${VOLUME_HOME}/.bashrc:/root/.bashrc
    image: python:3.6.5
    command:
    - /bin/sh
    - -c
    - "${INIT_COMMAND}"
    restart: always
